import { assertEquals } from '@std/assert';
import {
	CS_ADHOC,
	CS_ALLOWED_MACHO,
	CS_CHECK_EXPIRATION,
	CS_DATAVAULT_CONTROLLER,
	CS_ENFORCEMENT,
	CS_ENTITLEMENT_FLAGS,
	CS_GET_TASK_ALLOW,
	CS_HARD,
	CS_INSTALLER,
	CS_KILL,
	CS_LINKER_SIGNED,
	CS_NVRAM_UNRESTRICTED,
	CS_REQUIRE_LV,
	CS_RESTRICT,
	CS_RUNTIME,
	CSSLOT_ALTERNATE_CODEDIRECTORIES,
	CSSLOT_ALTERNATE_CODEDIRECTORY_LIMIT,
	CSSLOT_ALTERNATE_CODEDIRECTORY_MAX,
} from './cs_blobs.ts';

Deno.test('constant expressions', () => {
	assertEquals(
		CS_ALLOWED_MACHO,
		(
			CS_ADHOC |
			CS_HARD |
			CS_KILL |
			CS_CHECK_EXPIRATION |
			CS_RESTRICT |
			CS_ENFORCEMENT |
			CS_REQUIRE_LV |
			CS_RUNTIME |
			CS_LINKER_SIGNED
		) >>> 0,
	);
	assertEquals(
		CS_ENTITLEMENT_FLAGS,
		(
			CS_GET_TASK_ALLOW |
			CS_INSTALLER |
			CS_DATAVAULT_CONTROLLER |
			CS_NVRAM_UNRESTRICTED
		) >>> 0,
	);
	assertEquals(
		CSSLOT_ALTERNATE_CODEDIRECTORY_LIMIT,
		CSSLOT_ALTERNATE_CODEDIRECTORIES + CSSLOT_ALTERNATE_CODEDIRECTORY_MAX,
	);
});
