import { assertEquals } from '@std/assert';
import {
	CPU_ARCH_ABI64,
	CPU_ARCH_ABI64_32,
	CPU_SUBTYPE_386,
	CPU_SUBTYPE_486,
	CPU_SUBTYPE_486SX,
	CPU_SUBTYPE_586,
	CPU_SUBTYPE_ARM64_PTR_AUTH_VERSION,
	CPU_SUBTYPE_CELERON,
	CPU_SUBTYPE_CELERON_MOBILE,
	CPU_SUBTYPE_I386_ALL,
	CPU_SUBTYPE_INTEL,
	CPU_SUBTYPE_INTEL_FAMILY,
	CPU_SUBTYPE_INTEL_MODEL,
	CPU_SUBTYPE_ITANIUM,
	CPU_SUBTYPE_ITANIUM_2,
	CPU_SUBTYPE_PENT,
	CPU_SUBTYPE_PENTII_M3,
	CPU_SUBTYPE_PENTII_M5,
	CPU_SUBTYPE_PENTIUM_3,
	CPU_SUBTYPE_PENTIUM_3_M,
	CPU_SUBTYPE_PENTIUM_3_XEON,
	CPU_SUBTYPE_PENTIUM_4,
	CPU_SUBTYPE_PENTIUM_4_M,
	CPU_SUBTYPE_PENTIUM_M,
	CPU_SUBTYPE_PENTPRO,
	CPU_SUBTYPE_XEON,
	CPU_SUBTYPE_XEON_MP,
	CPU_TYPE_ARM,
	CPU_TYPE_ARM64,
	CPU_TYPE_ARM64_32,
	CPU_TYPE_POWERPC,
	CPU_TYPE_POWERPC64,
	CPU_TYPE_X86,
	CPU_TYPE_X86_64,
} from './machine.ts';

Deno.test('constant expressions', () => {
	assertEquals(CPU_TYPE_X86_64, CPU_TYPE_X86 | CPU_ARCH_ABI64);
	assertEquals(CPU_TYPE_ARM64, CPU_TYPE_ARM | CPU_ARCH_ABI64);
	assertEquals(CPU_TYPE_ARM64_32, CPU_TYPE_ARM | CPU_ARCH_ABI64_32);
	assertEquals(CPU_TYPE_POWERPC64, CPU_TYPE_POWERPC | CPU_ARCH_ABI64);

	assertEquals(CPU_SUBTYPE_I386_ALL, CPU_SUBTYPE_INTEL(3, 0));
	assertEquals(CPU_SUBTYPE_386, CPU_SUBTYPE_INTEL(3, 0));
	assertEquals(CPU_SUBTYPE_486, CPU_SUBTYPE_INTEL(4, 0));
	assertEquals(CPU_SUBTYPE_486SX, CPU_SUBTYPE_INTEL(4, 8));
	assertEquals(CPU_SUBTYPE_586, CPU_SUBTYPE_INTEL(5, 0));
	assertEquals(CPU_SUBTYPE_PENT, CPU_SUBTYPE_INTEL(5, 0));
	assertEquals(CPU_SUBTYPE_PENTPRO, CPU_SUBTYPE_INTEL(6, 1));
	assertEquals(CPU_SUBTYPE_PENTII_M3, CPU_SUBTYPE_INTEL(6, 3));
	assertEquals(CPU_SUBTYPE_PENTII_M5, CPU_SUBTYPE_INTEL(6, 5));
	assertEquals(CPU_SUBTYPE_CELERON, CPU_SUBTYPE_INTEL(7, 6));
	assertEquals(CPU_SUBTYPE_CELERON_MOBILE, CPU_SUBTYPE_INTEL(7, 7));
	assertEquals(CPU_SUBTYPE_PENTIUM_3, CPU_SUBTYPE_INTEL(8, 0));
	assertEquals(CPU_SUBTYPE_PENTIUM_3_M, CPU_SUBTYPE_INTEL(8, 1));
	assertEquals(CPU_SUBTYPE_PENTIUM_3_XEON, CPU_SUBTYPE_INTEL(8, 2));
	assertEquals(CPU_SUBTYPE_PENTIUM_M, CPU_SUBTYPE_INTEL(9, 0));
	assertEquals(CPU_SUBTYPE_PENTIUM_4, CPU_SUBTYPE_INTEL(10, 0));
	assertEquals(CPU_SUBTYPE_PENTIUM_4_M, CPU_SUBTYPE_INTEL(10, 1));
	assertEquals(CPU_SUBTYPE_ITANIUM, CPU_SUBTYPE_INTEL(11, 0));
	assertEquals(CPU_SUBTYPE_ITANIUM_2, CPU_SUBTYPE_INTEL(11, 1));
	assertEquals(CPU_SUBTYPE_XEON, CPU_SUBTYPE_INTEL(12, 0));
	assertEquals(CPU_SUBTYPE_XEON_MP, CPU_SUBTYPE_INTEL(12, 1));
});

Deno.test('constant: CPU_SUBTYPE_INTEL', () => {
	const subtype = CPU_SUBTYPE_INTEL(0x8, 0xfedcba9);
	assertEquals(subtype, 0xfedcba98);

	const family = CPU_SUBTYPE_INTEL_FAMILY(subtype);
	assertEquals(family, 0x8);

	const model = CPU_SUBTYPE_INTEL_MODEL(subtype);
	assertEquals(model, 0xfedcba9);
});

Deno.test('constant: CPU_SUBTYPE_ARM64', () => {
	assertEquals(CPU_SUBTYPE_ARM64_PTR_AUTH_VERSION(0x00000000), 0);
	assertEquals(CPU_SUBTYPE_ARM64_PTR_AUTH_VERSION(0x01000000), 1);
	assertEquals(CPU_SUBTYPE_ARM64_PTR_AUTH_VERSION(0x0f000000), 15);
});
